# Generated by Django 6.0.6 on 2026-06-20 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ICD10",
            fields=[
                (
                    "kode",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nama_penyakit", models.CharField(max_length=255)),
                ("kategori", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Obat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200, unique=True)),
                ("stok", models.IntegerField(default=0)),
                ("satuan", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Pasien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_rm", models.CharField(blank=True, max_length=20, unique=True)),
                ("nama", models.CharField(max_length=200)),
                ("tgl_lahir", models.DateField(blank=True, null=True)),
                ("alamat", models.TextField(blank=True)),
                ("no_telp", models.CharField(blank=True, max_length=20)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                        max_length=1,
                    ),
                ),
                ("pekerjaan", models.CharField(blank=True, max_length=100)),
                ("alergi", models.TextField(blank=True)),
                ("riwayat_penyakit", models.TextField(blank=True)),
                ("aktif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LogCetakSurat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jenis_surat", models.CharField(max_length=50)),
                ("tanggal_cetak", models.DateTimeField(auto_now_add=True)),
                (
                    "dicetak_oleh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pasien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rekam_medis.pasien",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RekamMedis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateTimeField(auto_now_add=True)),
                ("subjective", models.TextField()),
                ("objective", models.TextField(blank=True)),
                ("assessment", models.CharField(blank=True, max_length=255)),
                ("planning", models.TextField(blank=True)),
                ("lampiran_mega", models.URLField(blank=True)),
                (
                    "file_lampiran",
                    models.FileField(blank=True, null=True, upload_to="lampiran/"),
                ),
                (
                    "icd10",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rekam_medis.icd10",
                    ),
                ),
                (
                    "pasien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rekam_medis",
                        to="rekam_medis.pasien",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kunjungan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(auto_now_add=True)),
                (
                    "rekam_medis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rekam_medis.rekammedis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah", models.IntegerField()),
                ("aturan", models.TextField()),
                (
                    "obat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rekam_medis.obat",
                    ),
                ),
                (
                    "rekam_medis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resep",
                        to="rekam_medis.rekammedis",
                    ),
                ),
            ],
        ),
    ]
